services:
  neo4j:
    image: neo4j:5.5
    container_name: promcode-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_PLUGINS=["n10s"]
      - NEO4J_dbms_security_procedures_unrestricted=n10s.*
      - NEO4J_dbms_security_procedures_allowlist=n10s.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
      - ./scripts:/scripts
    networks:
      - promcode-network
    healthcheck:
      test: ["CMD-SHELL", "cypher-shell -u neo4j -p password123 'RETURN 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j-init:
    image: neo4j:5.5
    container_name: promcode-neo4j-init
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./scripts:/scripts
    networks:
      - promcode-network
    command: ["/scripts/init-neo4j.sh"]
    restart: "no"

  server:
    build:
      context: ./PROMCODE-server
      dockerfile: Dockerfile
    container_name: promcode-server
    ports:
      - "3000:3000"
    environment:
      - SERVER_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password123
    volumes:
      - ./PROMCODE-server/uploaded:/app/uploaded
    depends_on:
      neo4j:
        condition: service_healthy
      neo4j-init:
        condition: service_completed_successfully
    networks:
      - promcode-network

  client:
    build:
      context: ./PROMCODE-client
      dockerfile: Dockerfile
    container_name: promcode-client
    ports:
      - "8080:8080"
    environment:
      - VUE_APP_SERVER_URL=http://localhost:3000
    depends_on:
      - server
    networks:
      - promcode-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:

networks:
  promcode-network:
    driver: bridge
